### ISSUE TITLE
Mobile Bug: Scrolling stuck at top and bottom

### ISSUE THREAD

**Issue by orishim** [dOrgTech/landing-page-v2#135]
When you scroll past the top or past the bottom a white background appears and then the scrolling gets stuck,

Steps to reproduce:
1. Open home page on mobile
2. Scroll up past the top
3. Try scrolling down

https://user-images.githubusercontent.com/10736693/107994135-0097bd80-6faa-11eb-85b3-2c7aac53b822.mov

**Comment by krisbitney** [comment]
I tested this on the following mobile browsers:

- iphone: Safari, Chrome, Brave
- Android: Chrome, Brave

The issue was immediately apparent on Brave for iphone, but I was unable to replicate it with other browsers or on Android. This issue seems to be specific to Brave on iphone. I'll have to do more research to learn what could be causing it.

**Comment by benefacto** [comment]
This appears to be Brave specific, does not occur on Firefox

**Comment by krisbitney** [comment]
Ori confirmed he also experiences the bug in Safari

**Comment by krisbitney** [comment]
I think the issue may be related to overscrolling effects in iOS browsers. This is because overscrolling on iOS devices causes a "bounce" effect, not a page reload as on Android. I suspect the bounce effect somehow breaks the layout, but I don't have a causal mechanism in mind. This theory would be supported by confirmation that Brave browser for iOS uses a similar bounce effect on overscroll.

A potential fix would be to prevent overscroll in iOS, preferably without affecting Android overscroll effects. I can possibly implement custom overscrolling efffects in the future to improve UX, with a straightforward option being a page refresh.

Some links I intend to reference when I get a chance use someone's iphone for an extended period:
https://stackoverflow.com/questions/29894997/prevent-ios-bounce-without-disabling-scroll-ability
https://stackoverflow.com/questions/27335320/detect-the-end-of-overscroll
